export const STRING_CONSTANTS = Object.freeze({
    TOKEN_NAME : 'user',
    UNAUTHORIZED : 'Token not found',
    TOKEN_ISSUED : 'Token issued',
    TOKEN_EXPIRED : 'Token Expired',
    TOKEN_ISSUE_SUCCESS : 'Token issued successfully',
    TOKEN_ISSUE_ERROR : 'Token issuing failed',
    TOKEN_VERIFY_ERROR : 'Token verification error',
    TOKEN_INVALID : 'Invalid Token',
    SERVER : 'Server error',
    REGISTRATION_SUCCESS : 'Registration success',
    REGISTRATION_ERROR : 'Registration error',
    LOGIN_SUCCESS : 'Login success',
    LOGIN_ERROR : 'Login error',
    LOGOUT_SUCCESS : 'Logout successfully',
    LOGOUT_ERROR : 'Logout failed',
    USER_ALREADY_EXIST : 'User already exist',
    OTP_SENT : 'OTP sent to mail',
    OTP_SENT_ERROR : 'OTP sent failed',
    OTP_ERROR :'Invalid or expired OTP',
    RESET_OTP :'Password reset otp sent to your email',
    VERIFICATION_SUCCESS :'Verified successfully',
    VERIFICATION_ERROR : 'Verification failed',
    USER_NOT_FOUND : 'User not found',
    INVALID_PASSWORD : 'Incorrect password',
    LOGIN_SUCCESS : 'Login success',
    LOGIN_ERROR : 'Login error',
    GOOGLE_AUTH_SUCCESS : 'Google authentication successfull',
    GOOGLE_AUTH_ERROR : 'Google authentication failed',
    ACCOUNT_IS_DEACTIVATED : 'Account is deactivated',
    PASSWORD_RESET_SUCCESS : 'Password reset successfull',
    PASSWORD_RESET_ERROR : 'Password reset failed',
    PROFILE_UPDATION_ERROR : 'Profile updation error',
    ACCOUNT_DELETION_SUCCESS : 'Account deletion success',
    ACCOUNT_DELETION_FAILED : 'Account deletion failed',
    PROFILE_UPDATION_SUCCESS : 'Profile updation success',
    PROFILE_LOAD_ERROR : 'Error loading profile',
    PROFILE_LOAD_SUCCESS : 'Profile Load Success',
})

export const HTTP_STATUS = Object.freeze({
    // 1xx Informational
    CONTINUE: 100,
    SWITCHING_PROTOCOLS: 101,
    PROCESSING: 102,
  
    // 2xx Success
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NON_AUTHORITATIVE_INFORMATION: 203,
    NO_CONTENT: 204,
    RESET_CONTENT: 205,
    PARTIAL_CONTENT: 206,
    MULTI_STATUS: 207,
    ALREADY_REPORTED: 208,
    IM_USED: 226,
  
    // 3xx Redirection
    MULTIPLE_CHOICES: 300,
    MOVED_PERMANENTLY: 301,
    FOUND: 302,
    SEE_OTHER: 303,
    NOT_MODIFIED: 304,
    USE_PROXY: 305,
    TEMPORARY_REDIRECT: 307,
    PERMANENT_REDIRECT: 308,
  
    // 4xx Client Error
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    PAYMENT_REQUIRED: 402,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    NOT_ACCEPTABLE: 406,
    PROXY_AUTHENTICATION_REQUIRED: 407,
    REQUEST_TIMEOUT: 408,
    CONFLICT: 409,
    GONE: 410,
    LENGTH_REQUIRED: 411,
    PRECONDITION_FAILED: 412,
    PAYLOAD_TOO_LARGE: 413,
    URI_TOO_LONG: 414,
    UNSUPPORTED_MEDIA_TYPE: 415,
    RANGE_NOT_SATISFIABLE: 416,
    EXPECTATION_FAILED: 417,
    IM_A_TEAPOT: 418,
    MISDIRECTED_REQUEST: 421,
    UNPROCESSABLE_ENTITY: 422,
    LOCKED: 423,
    FAILED_DEPENDENCY: 424,
    UPGRADE_REQUIRED: 426,
    PRECONDITION_REQUIRED: 428,
    TOO_MANY_REQUESTS: 429,
    REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
    UNAVAILABLE_FOR_LEGAL_REASONS: 451,
  
    // 5xx Server Error
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
    HTTP_VERSION_NOT_SUPPORTED: 505,
    VARIANT_ALSO_NEGOTIATES: 506,
    INSUFFICIENT_STORAGE: 507,
    LOOP_DETECTED: 508,
    NOT_EXTENDED: 510,
    NETWORK_AUTHENTICATION_REQUIRED: 511
  })